name: banuba_arcloud
description: Our AR Cloud service enables your app to connect with our servers and access AR effects directly from the cloud.
version: 1.0.5
homepage: 'https://docs.banuba.com/'

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: '^1.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.banuba.sdk.flutter.arcloud
        pluginClass: FlutterARCloudPlugin
      ios:
        pluginClass: FlutterARCloudPlugin
